version: '3' 
volumes:
  local_postgres_data: {}
  local_filestore_data: {}
  pgadmin: {} 
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
        - db
    ports:
      - "8090:8069"
      - "8096:8071"
      - "8097:8072"
    volumes:
      - ./config:/etc/odoo
      - ./addons/:/mnt/extra-addons-abakus
      - ./filestore:/var/lib/odoo/filestore
    restart: always
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: --dev=all
  db:
    image: postgres:14
    ports:
      - "8098:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    restart: always
